services:
  - type: web
    name: kansas-food-pantry
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
