services:
  - type: web
    name: kansas-food-pantry
    env: python
    plan: pro
    buildCommand: |
      apt-get update && apt-get install -y gcc build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0.tar.gz
  
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: HF_TOKEN
        sync: false
