services:
  - type: web
    name: kansas-food-pantry
    env: python
<<<<<<< HEAD
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
=======
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
>>>>>>> d612625
