services:
  - type: web
    name: kansas-food-pantry
    env: python
    plan: standard
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: HF_TOKEN
        value: false

